'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { ArrowLeft, Check, Clipboard, Download, Eraser, FileJson, LockKeyhole } from 'lucide-react'

const sample = '{\n  "name": "DevKit",\n  "private": true,\n  "tools": ["json", "encoding"]\n}'

export default function JsonFormatterPage() {
  const [input, setInput] = useState(sample)
  const [mode, setMode] = useState<'format' | 'minify'>('format')
  const [copied, setCopied] = useState(false)
  const parsed = useMemo(() => { try { return { output: mode === 'format' ? JSON.stringify(JSON.parse(input), null, 2) : JSON.stringify(JSON.parse(input)), error: '' } } catch (error) { return { output: '', error: error instanceof Error ? error.message : 'Invalid JSON input.' } } }, [input, mode])
  const copy = async () => { if (!parsed.output) return; await navigator.clipboard.writeText(parsed.output); setCopied(true); setTimeout(() => setCopied(false), 1600) }
  const download = () => { if (!parsed.output) return; const blob = new Blob([parsed.output], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'formatted.json'; anchor.click(); URL.revokeObjectURL(url) }
  return <main className="min-h-screen bg-background text-foreground"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-8"><Link href="/" className="font-mono text-sm font-bold tracking-tight">DEVKIT</Link><span className="flex items-center gap-2 text-xs text-muted-foreground"><LockKeyhole className="size-3.5 text-accent" /> Processed locally</span></header><div className="mx-auto max-w-6xl px-5 pb-20 pt-12 lg:px-8"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Back to tools</Link><div className="max-w-2xl"><div className="mb-4 grid size-11 place-items-center rounded-lg border border-border text-accent"><FileJson className="size-5" /></div><h1 className="text-4xl font-semibold tracking-tight">JSON Formatter</h1><p className="mt-3 text-muted-foreground">Format, minify and validate JSON instantly. Nothing leaves your browser.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-2"><Editor label="Input" value={input} onChange={setInput} /><Editor label="Output" value={parsed.output} readOnly error={parsed.error} /></div><div className="mt-5 flex flex-wrap items-center gap-2"><button onClick={() => setMode('format')} className={`rounded-md border px-3 py-2 text-sm ${mode === 'format' ? 'border-accent text-accent' : 'border-border text-muted-foreground'}`}>Format</button><button onClick={() => setMode('minify')} className={`rounded-md border px-3 py-2 text-sm ${mode === 'minify' ? 'border-accent text-accent' : 'border-border text-muted-foreground'}`}>Minify</button><span className="flex-1" /><button onClick={() => setInput('')} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm text-muted-foreground hover:text-foreground"><Eraser className="size-4" /> Clear</button><button onClick={download} disabled={!parsed.output} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm text-muted-foreground hover:text-foreground disabled:opacity-40"><Download className="size-4" /> Download</button><button onClick={copy} disabled={!parsed.output} className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-40">{copied ? <Check className="size-4" /> : <Clipboard className="size-4" />} {copied ? 'Copied' : 'Copy result'}</button></div><div className="mt-8 flex items-center gap-2 text-xs text-muted-foreground"><Check className="size-3.5 text-accent" /> Valid JSON is ready to use. Keyboard shortcut: <kbd className="rounded border border-border px-1.5 py-0.5 font-mono">⌘ Enter</kbd></div></div></main>
}
function Editor({ label, value, onChange, readOnly, error }: { label: string; value: string; onChange?: (value: string) => void; readOnly?: boolean; error?: string }) { return <div className="overflow-hidden rounded-lg border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-4 py-3"><label className="font-mono text-xs uppercase tracking-wider text-muted-foreground">{label}</label>{error ? <span className="text-xs text-destructive">Invalid JSON</span> : <span className="font-mono text-[10px] text-muted-foreground">JSON</span>}</div><textarea aria-label={label} value={value} readOnly={readOnly} onChange={(event) => onChange?.(event.target.value)} spellCheck={false} className="min-h-80 w-full resize-y bg-background p-4 font-mono text-sm leading-6 outline-none placeholder:text-muted-foreground" placeholder="Paste JSON here..." />{error && <p className="border-t border-destructive/30 bg-destructive/10 px-4 py-3 text-xs text-destructive">{error}</p>}</div> }
