'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import QRCode from 'qrcode'
import semver from 'semver'
import { ToolShell, Actions, TextArea } from '@/components/devkit-tool-shell'

const button = 'rounded-md border border-border px-3 py-2 text-sm transition-colors hover:bg-muted disabled:opacity-40'
const primary = 'rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-40'
function download(text: string, name: string, type = 'text/plain') { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([text], { type })); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000) }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-8 rounded-xl border border-border bg-card p-5"><h2 className="font-mono text-xs uppercase tracking-wider text-muted-foreground">{title}</h2>{children}</section> }
function Field({ label, value, onChange, placeholder, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string; type?: string }) { return <label className="flex flex-col gap-2 text-sm"><span className="text-muted-foreground">{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e => onChange(e.target.value)} className="rounded-md border border-border bg-background px-3 py-2 outline-none focus:ring-2 focus:ring-ring" /></label> }
function ErrorText({ error }: { error: string }) { return error ? <p role="alert" className="mt-3 rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p> : null }

function HtmlTool() { const [input,setInput]=useState(''); const [mode,setMode]=useState<'encode'|'decode'>('encode'); const [out,setOut]=useState(''); const [error,setError]=useState(''); const run=()=>{try{ if(mode==='encode') setOut(input.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')); else { const el=document.createElement('textarea'); el.innerHTML=input; setOut(el.value) } setError('') }catch{setError('Unable to decode HTML entities.')}}; return <ToolShell title="HTML Encoder / Decoder" description="Encode or decode HTML entities locally in your browser."><div className="mt-8 flex gap-2"><button className={mode==='encode'?primary:button} onClick={()=>setMode('encode')}>Encode</button><button className={mode==='decode'?primary:button} onClick={()=>setMode('decode')}>Decode</button></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><TextArea label="Input" value={input} onChange={setInput} placeholder={mode==='encode'?'<div>Hello & welcome</div>':'&lt;div&gt;Hello &amp; welcome&lt;/div&gt;'} /><TextArea label="Output" value={out} onChange={()=>undefined} /></div><ErrorText error={error}/><Actions output={out} onCopy={()=>undefined} onClear={()=>{setInput('');setOut('');setError('')}} /><button className={primary} onClick={run}>Process {mode}</button></ToolShell> }

function formatCss(source: string) { let out='', indent=0, quote='', comment=false; for(let i=0;i<source.length;i++){const c=source[i], n=source[i+1]; if(comment){out+=c;if(c==='*'&&n==='/'){out+='/';i++;comment=false}continue} if(!quote&&c==='/'&&n==='*'){out+='/*';i++;comment=true;continue} if(quote){out+=c;if(c===quote&&source[i-1]!=='\\')quote='';continue} if(c==='"'||c==="'"){quote=c;out+=c;continue} if(c==='{'){out=out.trimEnd()+' {\n';indent++;out+='  '.repeat(indent)}else if(c==='}'){out=out.trimEnd()+'\n';indent=Math.max(0,indent-1);out+='  '.repeat(indent)+'}';if(source[i+1]!==';')out+='\n'+'  '.repeat(indent)}else if(c===';'){out=out.trimEnd()+';\n'+'  '.repeat(indent)}else if(c===':'){out=out.trimEnd()+': '}else out+=c} return out.split('\n').map(x=>x.trimEnd()).join('\n').trim() }
function CssTool() { const [input,setInput]=useState('');const [out,setOut]=useState('');const [error,setError]=useState('');const run=()=>{try{const opens=(input.match(/{/g)||[]).length, closes=(input.match(/}/g)||[]).length;if(opens!==closes)throw Error('Unbalanced CSS braces.');setOut(formatCss(input));setError('')}catch(e){setError(e instanceof Error?e.message:'Invalid CSS')}};return <ToolShell title="CSS Formatter" description="Format CSS while preserving strings, comments, URLs, and declarations."><div className="mt-8 grid gap-4 lg:grid-cols-2"><TextArea label="CSS input" value={input} onChange={setInput} placeholder="body{margin:0;padding:0}"/><TextArea label="Formatted CSS" value={out} onChange={()=>undefined}/></div><ErrorText error={error}/><div className="flex gap-2"><button className={primary} onClick={run}>Format</button><Actions output={out} onCopy={()=>undefined} onClear={()=>{setInput('');setOut('');setError('')}} /></div></ToolShell> }

function formatSql(source: string) { const keywords=/\b(SELECT|FROM|WHERE|LEFT JOIN|RIGHT JOIN|INNER JOIN|FULL JOIN|JOIN|ON|GROUP BY|ORDER BY|HAVING|LIMIT|VALUES|SET|INTO|UPDATE|DELETE FROM|INSERT INTO|CASE|WHEN|THEN|ELSE|END)\b/gi; let s=source.trim().replace(/\s+/g,' ').replace(/\s*,\s*/g,', '); s=s.replace(keywords, m=>`\n${m.toUpperCase()}`);s=s.replace(/\b(AND|OR)\b/gi,m=>`\n  ${m.toUpperCase()}`);return s.replace(/^\n/,'').replace(/;?$/,';').split('\n').map((line,i)=>i===0?line:line.trim()).join('\n') }
function SqlTool() {const [input,setInput]=useState('');const [out,setOut]=useState('');const [error,setError]=useState('');const run=()=>{if(!/\b(SELECT|INSERT|UPDATE|DELETE)\b/i.test(input)){setError('SQL must begin with SELECT, INSERT, UPDATE, or DELETE.');return}setError('');setOut(formatSql(input))};return <ToolShell title="SQL Formatter" description="Format common SQL statements into readable clauses."><div className="mt-8 grid gap-4 lg:grid-cols-2"><TextArea label="SQL input" value={input} onChange={setInput} placeholder="SELECT id,name FROM users WHERE active = true"/><TextArea label="Formatted SQL" value={out} onChange={()=>undefined}/></div><ErrorText error={error}/><div className="flex gap-2"><button className={primary} onClick={run}>Format SQL</button><Actions output={out} onCopy={()=>undefined} onClear={()=>{setInput('');setOut('');setError('')}}/></div></ToolShell>}

function QrTool(){const [input,setInput]=useState('');const [src,setSrc]=useState('');const [error,setError]=useState('');const run=async()=>{if(!input.trim()){setError('Enter text or a URL to generate a QR code.');setSrc('');return}try{setSrc(await QRCode.toDataURL(input,{width:320,margin:2,errorCorrectionLevel:'M'}));setError('')}catch{setError('Unable to generate this QR code. Try shorter text.')}};return <ToolShell title="QR Code Generator" description="Generate a real QR code locally from text, URLs, or contact information."><div className="mt-8 max-w-2xl"><Field label="Text or URL" value={input} onChange={setInput} placeholder="https://devkit-omega.vercel.app/"/><ErrorText error={error}/><div className="mt-4 flex gap-2"><button className={primary} onClick={run}>Generate QR Code</button><button className={button} onClick={()=>{setInput('');setSrc('');setError('')}}>Clear</button></div>{src&&<div className="mt-6 flex flex-col items-center gap-4 rounded-lg border border-border bg-white p-5"><img src={src} alt="Generated QR code" className="size-80 max-w-full"/><div className="flex gap-2"><button className={button} onClick={()=>download(src,'devkit-qr.png','image/png')}>Download PNG</button><button className={button} onClick={()=>navigator.clipboard.writeText(input)}>Copy value</button></div></div>}</div></ToolShell>}

const zones=['UTC','Asia/Kathmandu','Asia/Kolkata','Asia/Tokyo','Europe/London','Europe/Berlin','America/New_York','America/Chicago','America/Los_Angeles','Australia/Sydney']
function zonedParts(date: Date, zone: string){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23',timeZoneName:'short'}).formatToParts(date).reduce((a,p)=>(a[p.type]=p.value,a),{} as Record<string,string>)}
function zoneOffset(date: Date,zone:string){const p=zonedParts(date,zone);return Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)-date.getTime()}
function parseInZone(value:string,zone:string){const [d,t]=value.split('T');const [y,m,day]=d.split('-').map(Number),[h,mi]=t.split(':').map(Number);let guess=Date.UTC(y,m-1,day,h,mi);for(let i=0;i<3;i++)guess=Date.UTC(y,m-1,day,h,mi)-zoneOffset(new Date(guess),zone);return new Date(guess)}
function TimezoneTool(){const [value,setValue]=useState('2026-09-11T10:00');const [from,setFrom]=useState('Asia/Kathmandu');const [to,setTo]=useState('America/New_York');const [out,setOut]=useState('');const [error,setError]=useState('');const run=()=>{try{const date=parseInZone(value,from);if(Number.isNaN(date.getTime()))throw Error('Enter a valid date and time.');const p=zonedParts(date,to);const source=zonedParts(date,from);setOut(`Original: ${value.replace('T',' ')} (${from}, ${source.timeZoneName})\nConverted: ${p.year}-${p.month}-${p.day} ${p.hour}:${p.minute} (${to}, ${p.timeZoneName})\nISO: ${date.toISOString()}`);setError('')}catch(e){setError(e instanceof Error?e.message:'Invalid timezone conversion')}};return <ToolShell title="Timezone Converter" description="Convert local date and time between IANA timezones with DST-aware browser APIs."><div className="mt-8 grid gap-4 sm:grid-cols-3"><Field label="Date and time" type="datetime-local" value={value} onChange={setValue}/><label className="flex flex-col gap-2 text-sm"><span className="text-muted-foreground">From timezone</span><select value={from} onChange={e=>setFrom(e.target.value)} className="rounded-md border border-border bg-background px-3 py-2">{zones.map(z=><option key={z}>{z}</option>)}</select></label><label className="flex flex-col gap-2 text-sm"><span className="text-muted-foreground">To timezone</span><select value={to} onChange={e=>setTo(e.target.value)} className="rounded-md border border-border bg-background px-3 py-2">{zones.map(z=><option key={z}>{z}</option>)}</select></label></div><button className={`${primary} mt-4`} onClick={run}>Convert</button><ErrorText error={error}/>{out&&<pre className="mt-6 whitespace-pre-wrap rounded-lg border border-border bg-card p-4 font-mono text-sm">{out}</pre>}</ToolShell>}

function GitTool(){const [input,setInput]=useState('');const [out,setOut]=useState('');const [error,setError]=useState('');const run=()=>{const s=input.trim();let command='',explanation='';let m;if(/^initialize|^init/i.test(s)){command='git init';explanation='Initializes a new repository.'}else if((m=s.match(/clone\s+(https?:\/\/\S+)/i))){command=`git clone ${m[1]}`}else if((m=s.match(/(?:new )?branch called\s+([\w./-]+)/i))){command=`git switch -c ${m[1]}`}else if((m=s.match(/switch to\s+([\w./-]+)/i))){command=`git switch ${m[1]}`}else if((m=s.match(/delete (?:the )?branch\s+([\w./-]+)/i))){command=`git branch -d ${m[1]}`}else if((m=s.match(/commit .*message\s+["'](.+?)["']/i))){command=`git add . && git commit -m ${JSON.stringify(m[1])}`}else if((m=s.match(/push\s+([\w./-]+)\s+to\s+([\w./-]+)/i))){command=`git push ${m[2]} ${m[1]}`}else if(/^pull/i.test(s)){command='git pull'}else if(/status/i.test(s)){command='git status'}else if(/history|log/i.test(s)){command='git log --oneline'}else{setError('Could not identify a supported Git intent. Try “Create a new branch called feature/login”.');return}setOut(`${command}\n\n${explanation}`);setError('')};return <ToolShell title="Git Command Helper" description="Turn a natural-language Git request into a command. Commands are never executed."><TextArea label="Describe the Git task" value={input} onChange={setInput} placeholder="Create a new branch called feature/login"/><ErrorText error={error}/><button className={`${primary} mt-4`} onClick={run}>Generate Command</button>{out&&<><pre className="mt-6 whitespace-pre-wrap rounded-lg border border-border bg-card p-4 font-mono text-sm">{out}</pre><Actions output={out.split('\n\n')[0]} onCopy={()=>undefined} onClear={()=>{setInput('');setOut('')}}/></>}</ToolShell>}

function EnvTool(){const [input,setInput]=useState('');const [out,setOut]=useState('');const run=()=>{const seen=new Set<string>(),errors:string[]=[],warnings:string[]=[],lines=input.split(/\r?\n/);let count=0;for(const [i,raw] of lines.entries()){const line=raw.trim();if(!line||line.startsWith('#'))continue;const m=line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);if(!m){errors.push(`Line ${i+1}: invalid assignment.`);continue}count++;if(seen.has(m[1]))errors.push(`Line ${i+1}: duplicate variable ${m[1]}.`);seen.add(m[1]);if(!m[2])warnings.push(`Line ${i+1}: ${m[1]} has an empty value.`)}const masked=lines.map(line=>{const m=line.match(/^((?:export\s+)?[A-Za-z_][A-Za-z0-9_]*\s*=\s*)(.*)$/);return m&&/(KEY|SECRET|TOKEN|PASSWORD|PRIVATE|DATABASE)/i.test(m[1])?`${m[1]}********`:line}).join('\n');setOut(`Variables: ${count}\nErrors: ${errors.length}\nWarnings: ${warnings.length}\n${errors.concat(warnings).join('\n')||'Valid .env syntax.'}\n\nMasked preview:\n${masked}`)};return <ToolShell title=".env Validator" description="Validate environment syntax locally. Processed locally. Do not share real secrets."><TextArea label=".env input" value={input} onChange={setInput} placeholder="PORT=3000\nAPI_KEY=test123\nNODE_ENV=development"/><button className={`${primary} mt-4`} onClick={run}>Validate .env</button>{out&&<pre className="mt-6 whitespace-pre-wrap rounded-lg border border-border bg-card p-4 font-mono text-sm">{out}</pre>}</ToolShell>}

function SemverTool(){const [version,setVersion]=useState('1.5.2');const [range,setRange]=useState('>=1.0.0 <2.0.0');const [compare,setCompare]=useState('2.0.0');const [out,setOut]=useState('');const run=()=>{const v=semver.valid(version),r=semver.validRange(range),c=semver.valid(compare);if(!v) return setOut('Invalid version. Use a complete version such as 1.2.3.');if(!r)return setOut(`Invalid semver range: ${range}`);const result=semver.satisfies(v,r);const comparison=c?`\nComparison: ${semver.compare(v,c)===0?'equal to':semver.lt(v,c)?'less than':'greater than'} ${c}`:'';setOut(`${result?'✓':'✗'} ${v} ${result?'satisfies':'does not satisfy'} ${range}${comparison}`)};return <ToolShell title="Semver Calculator" description="Compare semantic versions and test npm-compatible version ranges."><div className="mt-8 grid gap-4 sm:grid-cols-3"><Field label="Version" value={version} onChange={setVersion}/><Field label="Range" value={range} onChange={setRange}/><Field label="Compare version (optional)" value={compare} onChange={setCompare}/></div><button className={`${primary} mt-4`} onClick={run}>Check Range</button>{out&&<pre className="mt-6 whitespace-pre-wrap rounded-lg border border-border bg-card p-4 font-mono text-sm">{out}</pre>}</ToolShell>}

function MetadataTool(){const [file,setFile]=useState<File|null>(null);const [src,setSrc]=useState('');const [info,setInfo]=useState('');const onFile=(f:File)=>{if(!f.type.startsWith('image/')){setInfo('Please select an image file.');return}if(f.size>25*1024*1024){setInfo('Image is too large. Choose a file under 25 MB.');return}const url=URL.createObjectURL(f);setFile(f);setSrc(url);const img=new Image();img.onload=()=>setInfo(`Filename: ${f.name}\nType: ${f.type}\nSize: ${(f.size/1024/1024).toFixed(2)} MB\nWidth: ${img.naturalWidth} px\nHeight: ${img.naturalHeight} px\nAspect ratio: ${(img.naturalWidth/img.naturalHeight).toFixed(2)}\n\nNo EXIF metadata found. Browser metadata is limited for this format.`);img.src=url};return <ToolShell title="Image Metadata Viewer" description="Inspect safe image metadata locally without uploading the file."><label className="mt-8 flex cursor-pointer flex-col items-center gap-2 rounded-xl border border-dashed border-border p-10 text-center hover:bg-muted"><span className="font-medium">Upload Image</span><span className="text-sm text-muted-foreground">PNG, JPEG, WEBP, GIF · up to 25 MB</span><input className="sr-only" type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/></label>{file&&<div className="mt-6 grid gap-6 md:grid-cols-[240px_1fr]"><img src={src} alt={`Preview of ${file.name}`} className="max-h-64 w-full rounded-lg object-cover"/><pre className="whitespace-pre-wrap rounded-lg border border-border bg-card p-4 font-mono text-sm">{info}</pre></div>}<button className={`${button} mt-4`} onClick={()=>{if(src)URL.revokeObjectURL(src);setFile(null);setSrc('');setInfo('')}} disabled={!file}>Remove image</button></ToolShell>}

function RequestTool(){const [method,setMethod]=useState('POST'),[url,setUrl]=useState('https://api.example.com/users'),[body,setBody]=useState('{\n  "name": "John"\n}'),[out,setOut]=useState('');const [headers,setHeaders]=useState([{k:'Content-Type',v:'application/json'}]);const generate=()=>{try{const parsed=new URL(url);const hs=headers.filter(x=>x.k.trim()&&x.v.trim());const curl=[`curl -X ${method} ${JSON.stringify(parsed.toString())}`,...hs.map(x=>`  -H ${JSON.stringify(`${x.k}: ${x.v}`)}`),body.trim()?`  -d ${JSON.stringify(body)}`:''].filter(Boolean).join(' \\\n');const fetch=`fetch(${JSON.stringify(parsed.toString())}, {\n  method: ${JSON.stringify(method)},\n  headers: ${JSON.stringify(Object.fromEntries(hs.map(x=>[x.k,x.v])),null,2)}${body.trim()?`,\n  body: ${JSON.stringify(body)}`:''}\n})`;setOut(`cURL:\n${curl}\n\nJavaScript Fetch:\n${fetch}`)}catch{setOut('Invalid URL. Enter a complete URL including https://.')}};return <ToolShell title="HTTP Request Builder" description="Generate cURL and JavaScript Fetch configurations locally. Requests are not sent."><div className="mt-8 grid gap-4 sm:grid-cols-[140px_1fr]"><label className="flex flex-col gap-2 text-sm"><span className="text-muted-foreground">Method</span><select value={method} onChange={e=>setMethod(e.target.value)} className="rounded-md border border-border bg-background px-3 py-2">{['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].map(x=><option key={x}>{x}</option>)}</select></label><Field label="URL" value={url} onChange={setUrl}/></div><div className="mt-4 flex flex-col gap-2 text-sm"><span className="text-muted-foreground">Headers</span>{headers.map((h,i)=><div className="flex gap-2" key={i}><input value={h.k} onChange={e=>setHeaders(x=>x.map((y,j)=>j===i?{...y,k:e.target.value}:y))} className="w-1/2 rounded-md border border-border bg-background px-3 py-2"/><input value={h.v} onChange={e=>setHeaders(x=>x.map((y,j)=>j===i?{...y,v:e.target.value}:y))} className="w-1/2 rounded-md border border-border bg-background px-3 py-2"/></div>)}<button className={button} onClick={()=>setHeaders(x=>[...x,{k:'',v:''}])}>Add header</button></div><div className="mt-4"><TextArea label="Body" value={body} onChange={setBody}/></div><button className={`${primary} mt-4`} onClick={generate}>Generate Configurations</button>{out&&<><pre className="mt-6 whitespace-pre-wrap rounded-lg border border-border bg-card p-4 font-mono text-sm">{out}</pre><Actions output={out} onCopy={()=>undefined} onClear={()=>setOut('')}/></>}</ToolShell>}

export function SpecializedTool({ id }: { id: string }) { if(id==='html-encoder')return <HtmlTool/>;if(id==='css-formatter')return <CssTool/>;if(id==='sql-formatter')return <SqlTool/>;if(id==='qr-code')return <QrTool/>;if(id==='timezone-converter')return <TimezoneTool/>;if(id==='git-helper')return <GitTool/>;if(id==='env-validator')return <EnvTool/>;if(id==='semver-calculator')return <SemverTool/>;if(id==='image-metadata')return <MetadataTool/>;if(id==='http-request')return <RequestTool/>;return null }

export const specializedIds = new Set(['html-encoder','css-formatter','sql-formatter','qr-code','timezone-converter','git-helper','env-validator','semver-calculator','image-metadata','http-request'])
